apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - max:
      cpu: 3
      memory: 1536Mi
    min:
      cpu: 17m
      memory: 90Mi
    type: Pod
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 60m
      memory: 307Mi
    max:
      cpu: 3
      memory: 1536Mi
    min:
      cpu: 17m
      memory: 90Mi
    type: Container
  - max:
      storage: 1Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim