---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/iconUrl: img/icons/java.svg
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: maven-shell
    version: 2.2.303
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-maven-shell
data:
  catalog-maven-shell.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "692764ddc65dfe31586a49a466060b5bf223f6f5"
        fabric8.io/iconUrl: "img/icons/java.svg"
        fabric8.io/git-branch: "release-v2.2.303"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "maven-shell"
        version: "2.2.303"
        group: "io.fabric8.devops.apps"
      name: "maven-shell"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/java.svg"
          fabric8.io/git-commit: "692764ddc65dfe31586a49a466060b5bf223f6f5"
          fabric8.io/git-branch: "release-v2.2.303"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=maven-shell&var-version=2.2.303"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "maven-shell"
          version: "2.2.303"
          group: "io.fabric8.devops.apps"
        name: "maven-shell"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "maven-shell"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "img/icons/java.svg"
              fabric8.io/git-commit: "692764ddc65dfe31586a49a466060b5bf223f6f5"
              fabric8.io/git-branch: "release-v2.2.303"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=maven-shell&var-version=2.2.303"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "maven-shell"
              version: "2.2.303"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/maven-builder:2.2.303"
              imagePullPolicy: "IfNotPresent"
              name: "maven-shell"
              ports: []
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: true
              volumeMounts:
              - mountPath: "/var/run/docker.sock"
                name: "data"
                readOnly: false
              - mountPath: "/root/.m2"
                name: "jenkins-maven-settings"
                readOnly: false
              - mountPath: "/root/workspaces"
                name: "workspace"
                readOnly: false
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - hostPath:
                path: "/home/maven-shell/workspaces"
              name: "workspace"
            - name: "jenkins-maven-settings"
              secret:
                items: []
                secretName: "jenkins-maven-settings"
            - hostPath:
                path: "/var/run/docker.sock"
              name: "data"
    parameters: []
