---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/git-branch: release-v2.2.303
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.303
    group: io.fabric8.devops.apps
    expose: "true"
  name: gogs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    project: gogs
    provider: fabric8
    group: io.fabric8.devops.apps
