---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: jenkins-docker-cfg
data:
  config.json: ""
type: fabric8.io/jenkins-docker-cfg
