---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    api.service.kubernetes.io/path: /blue
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.2.303
  labels:
    project: jenkins
    provider: fabric8
    expose: "true"
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: jenkins
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: jenkins
    provider: fabric8
    group: io.fabric8.devops.apps
