---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/gogs/2.2.303/gogs-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    group: io.fabric8.devops.apps
    project: gogs
    repository: gogs
    scm: git
    version: 2.2.303
  name: default-gogs-git
  namespace: user-secrets-source-admin
data:
  password: UmVkSGF0JDE=
  username: Z29nc2FkbWlu
