---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-docker-registry/src/main/fabric8/icon.png
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/git-branch: release-v2.2.303
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-docker-registry&var-version=2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/fabric8-docker-registry/2.2.303/fabric8-docker-registry-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: fabric8-docker-registry
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: fabric8-docker-registry
spec:
  replicas: 1
  selector:
    provider: fabric8
    project: fabric8-docker-registry
    group: io.fabric8.devops.apps
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-docker-registry/src/main/fabric8/icon.png
        fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
        fabric8.io/git-branch: release-v2.2.303
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-docker-registry&var-version=2.2.303
      labels:
        provider: fabric8
        project: fabric8-docker-registry
        version: 2.2.303
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry:2
        imagePullPolicy: IfNotPresent
        name: fabric8-docker-registry
        ports:
        - containerPort: 5000
          name: http
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
  triggers:
  - type: ConfigChange
