---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.console/summary: '[Fabric8 Console](http://fabric8.io/v2/console.html)
      for working with Fabric8 and Kubernetes'
    description: Creates an instance of the <a href="http://fabric8.io/v2/console.html">Fabric8 Console</a> for working with fabric8 and kubernetes.
    expose.config.fabric8.io/oauth-authorize-url-key: oauth-authorize-uri
    fabric8.console/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/platform/console/fabric8-console/2.2.199/fabric8-console-2.2.199.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: fabric8-console
    version: 2.2.199
    group: io.fabric8.platform.console
  name: fabric8
data:
  github-oauth-client-id: ${GITHUB_OAUTH_CLIENT_ID}
  github-oauth-client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
  oauth-authorize-uri: ""
  auth-mode: basic
  master-uri: k8s
