---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/gogs/2.2.303/gogs-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    group: io.fabric8.devops.apps
    project: gogs
    version: 2.2.303
  name: gogs
