---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/nexus/2.2.303/nexus-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: nexus
    version: 2.2.303
    group: io.fabric8.devops.apps
    expose: "true"
  name: nexus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    project: nexus
    provider: fabric8
    group: io.fabric8.devops.apps
