---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/online/packages/app-catalog/1.0-SNAPSHOT/app-catalog-1.0-SNAPSHOT.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: prometheus-blackbox-exporter
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: prometheus-blackbox-exporter
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9115"
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
    labels:
      expose: "true"
      provider: fabric8
      project: prometheus-blackbox-exporter
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: blackbox-exporter
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9115
    selector:
      project: prometheus-blackbox-exporter
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      provider: fabric8
      project: prometheus-blackbox-exporter
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: blackbox-exporter
  data:
    config.yml: |-
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_status_codes: []  # Defaults to 2xx
            method: GET
            no_follow_redirects: false
            fail_if_ssl: false
            fail_if_not_ssl: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.303
    labels:
      provider: fabric8
      project: prometheus-blackbox-exporter
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: prometheus-blackbox-expo
  spec:
    replicas: 1
    selector:
      project: prometheus-blackbox-exporter
      provider: fabric8
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.303
        labels:
          provider: fabric8
          project: prometheus-blackbox-exporter
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - image: prom/blackbox-exporter:master
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          name: blackbox-exporter
          ports:
          - containerPort: 9115
            name: http
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          volumeMounts:
          - mountPath: /etc/blackbox_exporter
            name: config-volume
        volumes:
        - configMap:
            name: blackbox-exporter
          name: config-volume
    triggers:
    - type: ConfigChange
