---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/online/packages/app-catalog/1.0-SNAPSHOT/app-catalog-1.0-SNAPSHOT.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: taiga
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: taiga
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: taiga
      expose: "true"
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: taiga
  spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      provider: fabric8
      project: taiga
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: taiga
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: taiga-back
  spec:
    ports:
    - port: 8000
      targetPort: 8000
    selector:
      provider: fabric8
      project: taiga
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: taiga
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: taiga-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=taiga&var-version=2.2.303
    labels:
      provider: fabric8
      project: taiga
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: taiga
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: taiga
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=taiga&var-version=2.2.303
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/var/lib/postgresql/data/","/usr/local/taiga/media","/usr/local/taiga/static"],"volumeMounts":[{"mountPath":"/var/lib/postgresql/data/","name":"taiga-data"},{"mountPath":"/usr/local/taiga/media","name":"taiga-media"},{"mountPath":"/usr/local/taiga/static","name":"taiga-static"}]}]'
        labels:
          provider: fabric8
          project: taiga
          version: 2.2.303
          group: io.fabric8.devops.apps
        name: taiga
      spec:
        containers:
        - env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: taiga
          image: postgres
          name: taiga-postgres
          volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: taiga-data
        - env:
          - name: SECRET_KEY
            value: xyz
          - name: POSTGRES_PORT_5432_TCP_ADDR
            value: 127.0.0.1
          - name: POSTGRES_ENV_POSTGRES_USER
            value: taiga
          - name: POSTGRES_ENV_POSTGRES_PASSWORD
            value: password
          image: fabric8/taiga-back:2.2.303
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: taiga-backend
          ports:
          - containerPort: 8000
            name: irdmi
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: taiga-data
          - mountPath: /usr/local/taiga/static
            name: taiga-static
          - mountPath: /usr/local/taiga/media
            name: taiga-media
        - image: fabric8/taiga-front:2.2.303
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: taiga-frontend
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: taiga-data
          - mountPath: /usr/local/taiga/static
            name: taiga-static
          - mountPath: /usr/local/taiga/media
            name: taiga-media
        volumes:
        - name: taiga-data
          persistentVolumeClaim:
            claimName: taiga-data
        - name: taiga-static
        - name: taiga-media
    triggers:
    - type: ConfigChange
