---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: img/icons/java.svg
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/online/packages/app-catalog/1.0-SNAPSHOT/app-catalog-1.0-SNAPSHOT.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: maven-shell
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: maven-shell
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/java.svg
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=maven-shell&var-version=2.2.303
    labels:
      provider: fabric8
      project: maven-shell
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: maven-shell
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: maven-shell
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/java.svg
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=maven-shell&var-version=2.2.303
        labels:
          provider: fabric8
          project: maven-shell
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/maven-builder:2.2.303
          imagePullPolicy: IfNotPresent
          name: maven-shell
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: data
            readOnly: false
          - mountPath: /root/.m2
            name: jenkins-maven-settings
            readOnly: false
          - mountPath: /root/workspaces
            name: workspace
            readOnly: false
        volumes:
        - hostPath:
            path: /home/maven-shell/workspaces
          name: workspace
        - name: jenkins-maven-settings
          secret:
            secretName: jenkins-maven-settings
        - hostPath:
            path: /var/run/docker.sock
          name: data
    triggers:
    - type: ConfigChange
