---
apiVersion: v1
kind: OAuthClient
metadata:
  annotations:
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/gogs/2.2.303/gogs-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: gogs
redirectURIs:
- http://localhost:3000
