---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/nexus/2.2.303/nexus-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: nexus
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: nexus-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
