kind: ConfigMap
apiVersion: v1
metadata:
  name: fabric8-space-link
  annotations:
    description: Links this namespace to the Space that contains all the environments
  labels:
    fabric8.io/kind: space-link
    provider: fabric8.io
    version: ${project.version}
data:
  space: ${PROJECT_NAMESPACE}
