---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
  name: content-repository
spec:
  type: ExternalName
  externalName: content-repository.${PROJECT_NAME}-jenkins
  ports:
  - port: 80
