apiVersion: v1
kind: RoleBinding
metadata:
  name: system:deployers
  namespace: ${PROJECT_NAME}
roleRef:
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
userNames:
- system:serviceaccount:${PROJECT_NAME}:deployer