apiVersion: v1
kind: RoleBinding
metadata:
  name: jenkins-view
  namespace: ${PROJECT_NAME}
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: jenkins
userNames:
- system:serviceaccount:${PROJECT_NAME}-jenkins:jenkins