---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/fabric8-planner/src/main/fabric8/icon.png
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-planner&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: fabric8-planner
      version: 1.0-SNAPSHOT
      group: io.fabric8.online.apps
    name: fabric8-planner
  spec:
    replicas: 1
    selector:
      project: fabric8-planner
      provider: fabric8
      group: io.fabric8.online.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/fabric8-planner/src/main/fabric8/icon.png
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-planner&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: fabric8-planner
          version: 1.0-SNAPSHOT
          group: io.fabric8.online.apps
      spec:
        containers:
        - command:
          - /bin/operator
          - operate
          image: funktion/funktion:1.0.6
          imagePullPolicy: IfNotPresent
          name: funktion
    triggers:
    - type: ConfigChange
