spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "WS_K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "ws_k8s_api_server"
              name: "fabric8-ui"
        - name: "K8S_API_SERVER_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              key: "k8s_api_server_protocol"
              name: "fabric8-ui"
        - name: "K8S_API_SERVER_BASE_PATH"
          valueFrom:
            configMapKeyRef:
              key: "k8s_api_server_base_path"
              name: "fabric8-ui"
        - name: "OAUTH_ISSUER"
          valueFrom:
            configMapKeyRef:
              key: "oauth_issuer"
              name: "fabric8-ui"
        - name: "OAUTH_CLIENT_ID"
          valueFrom:
            configMapKeyRef:
              key: "oauth_client_id"
              name: "fabric8-ui"
        - name: "OAUTH_SCOPE"
          valueFrom:
            configMapKeyRef:
              key: "oauth_scope"
              name: "fabric8-ui"
        - name: "OAUTH_AUTHORIZE_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth_authorize_uri"
              name: "fabric8-ui"
        - name: "AUTH_LOGOUT_URI"
          valueFrom:
            configMapKeyRef:
              key: "auth_logout_uri"
              name: "fabric8-ui"
        - name: "FABRIC8_PIPELINES_NAMESPACE"
          valueFrom:
            configMapKeyRef:
              key: "fabric8_pipelines_namespace"
              name: "fabric8-ui"
        image: "${image.registry}/${image.organisation}/fabric8-ui:${fabric8-ui.version}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10