metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "fabric8-ui"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "OAUTH_ISSUER"
          valueFrom:
            configMapKeyRef:
              key: "oauth-issuer"
              name: "fabric8-ui"
        - name: "OAUTH_LOGOUT_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth-logout-uri"
              name: "fabric8-ui"
        - name: "OAUTH_CLIENT_ID"
          valueFrom:
            configMapKeyRef:
              key: "oauth-client-id"
              name: "fabric8-ui"
        - name: "OAUTH_AUTHORIZE_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth-authorize-uri"
              name: "fabric8-ui"
        image: "fabric8/fabric8-runtime-console:${fabric8-ui.version}"
        imagePullPolicy: "IfNotPresent"
        name: fabric8-ui
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 120
          timeoutSeconds: 10
        ports:
        - containerPort: 8001
          name: "http"
      serviceAccountName: "fabric8-ui"