---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/git-branch: release-v2.2.303
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins&var-version=2.2.303
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: fabric8
      project: jenkins
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
        fabric8.io/secret-ssh-key: jenkins-git-ssh,jenkins-master-ssh
        fabric8.io/secret-ssh-config: jenkins-ssh-config
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins&var-version=2.2.303
        fabric8.io/secret-gpg-key: jenkins-release-gpg
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
        fabric8.io/secret-maven-settings: jenkins-maven-settings
        fabric8.io/git-branch: release-v2.2.303
        fabric8.io/secret-hub-api-token: jenkins-hub-api-token
        fabric8.io/secret-docker-cfg: jenkins-docker-cfg
        pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/home/jenkins/.docker","/var/jenkins_home/workspace","/var/jenkins_home/jobs","/var/run/docker.sock"],"volumeMounts":[{"mountPath":"/var/run/docker.sock","name":"data"},{"mountPath":"/home/jenkins/.docker","name":"jenkins-docker-cfg"},{"mountPath":"/var/jenkins_home/jobs","name":"jenkins-jobs"},{"mountPath":"/var/jenkins_home/workspace","name":"jenkins-workspace"}]}]'
      labels:
        provider: fabric8
        project: jenkins
        version: 2.2.303
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: PROJECT_VERSION
          valueFrom:
            configMapKeyRef:
              key: project-version
              name: jenkins
        - name: PIPELINE_ELASTICSEARCH_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: pipeline-elasticsearch-protocol
              name: jenkins
        - name: JENKINS_GOGS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-password
              name: jenkins
        - name: JENKINS_GOGS_USER
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-user
              name: jenkins
        - name: JENKINS_GOGS_EMAIL
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-email
              name: jenkins
        - name: PIPELINE_ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              key: pipeline-elasticsearch-host
              name: jenkins
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default
        image: fabric8/jenkins-docker:2.2.303
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /blue/
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: jenkins
        ports:
        - containerPort: 50000
          name: slave
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /blue/
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: data
          readOnly: false
        - mountPath: /home/jenkins/.docker
          name: jenkins-docker-cfg
          readOnly: false
        - mountPath: /var/jenkins_home/jobs
          name: jenkins-jobs
          readOnly: false
        - mountPath: /var/jenkins_home/workspace
          name: jenkins-workspace
          readOnly: false
      serviceAccountName: jenkins
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: data
      - name: jenkins-docker-cfg
        secret:
          secretName: jenkins-docker-cfg
      - name: jenkins-jobs
        persistentVolumeClaim:
          claimName: jenkins-jobs
      - name: jenkins-workspace
        persistentVolumeClaim:
          claimName: jenkins-workspace
