apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ${PROJECT_DESCRIPTION}
    openshift.io/display-name: ${PROJECT_DISPLAYNAME}
    openshift.io/requester: ${PROJECT_REQUESTING_USER}
  name: ${PROJECT_NAME}