apiVersion: v1
kind: ProjectRequest
metadata:
  annotations:
    openshift.io/description: ${PROJECT_DESCRIPTION} Run Environment
    openshift.io/display-name: ${PROJECT_DISPLAYNAME} Run
    openshift.io/requester: ${PROJECT_REQUESTING_USER}
  name: ${PROJECT_NAME}-run