---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/app-menu: development
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    expose: "false"
  name: "che-host"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "che"
    provider: "fabric8"
