---
name: "console"
home: "http://fabric8.io/packages/console/"
sources:
- "http://github.com/fabric8io/fabric8-online/packages/console"
version: "1.0-SNAPSHOT"
description: "The Fabric8 Microservices Console"
maintainers:
- name: "Fabric8 Development Team"
  email: "fabric8@googlegroups.com"
icon: "https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg"
