---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/artifactory/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/online/packages/app-catalog/1.0-SNAPSHOT/app-catalog-1.0-SNAPSHOT.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: artifactory
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: artifactory
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/artifactory/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: artifactory
      version: 2.2.303
      group: io.fabric8.devops.apps
      expose: "true"
    name: artifactory
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
    selector:
      project: artifactory
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/artifactory/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=artifactory&var-version=2.2.303
    labels:
      provider: fabric8
      project: artifactory
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: artifactory
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: artifactory
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/artifactory/src/main/fabric8/icon.png
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=artifactory&var-version=2.2.303
        labels:
          provider: fabric8
          project: artifactory
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: jfrog-docker-registry.bintray.io/artifactory/artifactory-oss
          name: artifactory
          ports:
          - containerPort: 8081
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
    triggers:
    - type: ConfigChange
