---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.303
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/configmapcontroller/2.2.303/configmapcontroller-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: configmapcontroller
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: configmapcontroller
spec:
  replicas: 1
  selector:
    project: configmapcontroller
    provider: fabric8
    group: io.fabric8.devops.apps
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.303
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.303
      labels:
        provider: fabric8
        project: configmapcontroller
        version: 2.2.303
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/configmapcontroller:2.3.3
        name: configmapcontroller
      serviceAccountName: configmapcontroller
  triggers:
  - type: ConfigChange
