---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/exposecontroller/2.2.303/exposecontroller-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: exposecontroller
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: exposecontroller
data:
  config.yml: |
    domain:
    exposer:
