---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    maven.fabric8.io/source-url: jar:file:/Users/jamesrawlings/.m2/repository/io/fabric8/devops/apps/jenkins/2.2.303/jenkins-2.2.303.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.303
    group: io.fabric8.devops.apps
  name: jenkins-git-ssh
data:
  ssh-key: ""
  ssh-key.pub: ""
type: fabric8.io/jenkins-git-ssh
