---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.309
  labels:
    provider: fabric8
    name: hubot-slack
    project: chat-slack
    version: 2.4.19
    expose: "true"
    group: io.fabric8.devops.apps
  name: chat-slack
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-slack/2.2.309/hubot-slack-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      expose: "true"
      project: hubot-slack
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot
  spec:
    ports:
    - port: 80
      targetPort: 8080
    selector:
      name: hubot-slack
      project: hubot-slack
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-notifier/2.2.309/hubot-notifier-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: hubot-notifier
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot-notifier
  spec:
    ports:
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      project: hubot-notifier
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.hubot-notifier/summary: Watches the OpenShift environment and notifies Hubot of events such as builds completing or failing
      description: Watches the OpenShift environment and notifies Hubot of events such as builds completing or failing.
      fabric8.hubot-notifier/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
      fabric8.io/json-schema: |-
        {
          "type" : "object",
          "properties" : {
            "HUBOT_USERNAME" : {
              "type" : "string",
              "description" : "The username for Hubot to login to the chat service",
              "default" : "fabric8"
            },
            "KUBERNETES_DNS_DOMAIN" : {
              "type" : "string",
              "description" : "The DNS domain added to the serviceName.namespace.svc. to make the DNS name",
              "default" : "cluster.local"
            },
            "HUBOT_PASSWORD" : {
              "type" : "string",
              "description" : "The password for Hubot to login to the chat service",
              "default" : "RedHat$1"
            }
          }
        }
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-notifier/2.2.309/hubot-notifier-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: hubot-notifier
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot-notifier
  data:
    hubot-password: RedHat$1
    kubernetes-dns-domain: cluster.local
    hubot-username: fabric8
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/json-schema: |-
        {
          "type" : "object",
          "properties" : {
            "HUBOT_SLACK_GRAFANA_HOST" : {
              "type" : "string",
              "description" : "Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'",
              "default" : "http://grafana.default.svc.cluster.local"
            },
            "HUBOT_SLACK_GRAFANA_API_KEY" : {
              "type" : "string",
              "description" : "API key for a particular user"
            },
            "HUBOT_JENKINS_URL" : {
              "type" : "string",
              "description" : "The URL for the Jenkins CI server",
              "default" : "http://jenkins.default.svc.cluster.local"
            },
            "HUBOT_SLACK_TOKEN" : {
              "type" : "string",
              "description" : "The token for Hubot to login to Slack"
            }
          }
        }
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-slack/2.2.309/hubot-slack-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      name: hubot-slack
      provider: fabric8
      project: hubot-slack
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot-slack
  data:
    hubot-jenkins-url: http://jenkins/
    hubot-grafana-host: http://grafana/
    hubot-slack-token: ${HUBOT_SLACK_TOKEN}
    hubot-grafana-api-key: ${HUBOT_SLACK_GRAFANA_API_KEY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/git-branch: release-v2.2.309
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-notifier/2.2.309/hubot-notifier-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: hubot-notifier
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot-notifier
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: hubot-notifier
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
          fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
          fabric8.io/git-branch: release-v2.2.309
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.309
        labels:
          provider: fabric8
          project: hubot-notifier
          version: 2.2.309
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: HUBOT_KUBERNETES_ROOM
            value: '#fabric8_${namespace}'
          - name: HUBOT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: hubot-username
                name: hubot-notifier
          - name: HUBOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: hubot-password
                name: hubot-notifier
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HUBOT_BUILD_ROOM
            value: '#fabric8_${namespace}'
          image: fabric8/hubot-notifier:2.2.309
          imagePullPolicy: IfNotPresent
          name: hubot-notifier
          ports:
          - containerPort: 8778
            name: jolokia
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: false
        serviceAccountName: fabric8
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/hubot-slack/2.2.309/hubot-slack-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      name: hubot-slack
      provider: fabric8
      project: hubot-slack
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: hubot-slack
  spec:
    replicas: 1
    selector:
      name: hubot-slack
      project: hubot-slack
      provider: fabric8
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v2.2.309
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.309
        labels:
          name: hubot-slack
          provider: fabric8
          project: hubot-slack
          version: 2.2.309
          group: io.fabric8.devops.apps
        name: hubot-slack
      spec:
        containers:
        - env:
          - name: HUBOT_GRAFANA_API_KEY
            valueFrom:
              configMapKeyRef:
                key: hubot-grafana-api-key
                name: hubot-slack
          - name: HUBOT_SLACK_TOKEN
            valueFrom:
              configMapKeyRef:
                key: hubot-slack-token
                name: hubot-slack
          - name: HUBOT_GRAFANA_HOST
            valueFrom:
              configMapKeyRef:
                key: hubot-grafana-host
                name: hubot-slack
          - name: HUBOT_JENKINS_URL
            valueFrom:
              configMapKeyRef:
                key: hubot-jenkins-url
                name: hubot-slack
          image: fabric8/hubot-slack:2.2.309
          name: hubot-slack
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
    triggers:
    - type: ConfigChange
