---
apiVersion: v1
kind: Template
metadata:
  annotations:
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/funktion-operator/src/main/fabric8/icon.png
  labels:
    provider: fabric8
    project: funktion-operator
    version: 1.0-SNAPSHOT
    group: io.fabric8.online.apps
  name: funktion-operator
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      provider: fabric8
      project: funktion-operator
      version: 1.0-SNAPSHOT
      group: io.fabric8.online.apps
    name: funktion-operator
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/funktion-operator/src/main/fabric8/icon.png
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=funktion-operator&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: funktion-operator
      version: 1.0-SNAPSHOT
      group: io.fabric8.online.apps
    name: funktion-operator
  spec:
    replicas: 1
    selector:
      project: funktion-operator
      provider: fabric8
      group: io.fabric8.online.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/funktion-operator/src/main/fabric8/icon.png
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=funktion-operator&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: funktion-operator
          version: 1.0-SNAPSHOT
          group: io.fabric8.online.apps
      spec:
        containers:
        - command:
          - /bin/operator
          - operate
          image: funktion/funktion:1.0.6
          imagePullPolicy: IfNotPresent
          name: funktion
        serviceAccountName: funktion-operator
    triggers:
    - type: ConfigChange
