---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.2.303
  labels:
    provider: fabric8
    project: gitlab
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: gitlab
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.303
    labels:
      project: gitlab
      provider: fabric8
      expose: "true"
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gitlab
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      project: gitlab
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.303
    labels:
      project: gitlab
      provider: fabric8
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gitlab-ssh
  spec:
    ports:
    - port: 22
      protocol: TCP
      targetPort: 22
    selector:
      project: gitlab
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.gitlab/summary: '[Gitlab](http://gitlab.com/) - A self-hosted Git service'
      description: "Gitlab is a self-hosted Git service      \n\nMore details on the\
        \ <a href=\"http://gitlab.com/\" target=\"gitlab\">Gitlab home page</a>.\n"
      fabric8.io/json-schema: |-
        {
          "type" : "object",
          "properties" : {
            "JENKINS_GITLAB_USER" : {
              "type" : "string",
              "description" : "The user name for Jenkins to login to Gitlab",
              "default" : "jenkins"
            },
            "JENKINS_GITLAB_PASSWORD" : {
              "type" : "string",
              "description" : "The password for Jenkins to login to Gitlab",
              "default" : "RedHat$1"
            },
            "GITLAB_URL" : {
              "type" : "string",
              "description" : "The GitLab server URL",
              "default" : "gitlab.vagrant.f8"
            },
            "JENKINS_GITLAB_EMAIL" : {
              "type" : "string",
              "description" : "The email address of the Jenkins user on Gitlab",
              "default" : "gitlab@fabric8.local"
            }
          }
        }
    labels:
      provider: fabric8
      project: gitlab
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gitlab
  data:
    jenkins-gitlab-password: RedHat$1
    gitlab-url: gitlab.vagrant.f8
    jenkins-gitlab-user: jenkins
    jenkins-gitlab-email: gitlab@fabric8.local
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gitlab&var-version=2.2.303
    labels:
      provider: fabric8
      project: gitlab
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: gitlab
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: gitlab
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gitlab/src/main/fabric8/icon.svg
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gitlab&var-version=2.2.303
        labels:
          provider: fabric8
          project: gitlab
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gitlab/gitlab-ce
          imagePullPolicy: IfNotPresent
          name: gitlab
          ports:
          - containerPort: 22
            name: ssh
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
    triggers:
    - type: ConfigChange
