---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
  labels:
    provider: fabric8
    project: grafana
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: grafana
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      expose: "true"
      project: grafana
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: grafana
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      project: grafana
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: grafana
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: grafana-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.303
    labels:
      provider: fabric8
      project: grafana
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: grafana
  spec:
    replicas: 1
    selector:
      project: grafana
      provider: fabric8
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.303
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/var/lib/grafana"],"volumeMounts":[{"mountPath":"/var/lib/grafana","name":"data-volume"}]}]'
        labels:
          provider: fabric8
          project: grafana
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: PROMETHEUS_ADDRESS
            value: http://prometheus
          image: fabric8/grafana:2.6.1
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 5
          name: grafana
          ports:
          - containerPort: 3000
            name: http
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 5
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: data-volume
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: grafana-data
    triggers:
    - type: ConfigChange
