---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 0221779c01265c45149182dbc9860c1b5eeee98e
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/build-id: "4"
    fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/4
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: release-v1.0.26
    fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0221779c01265c45149182dbc9860c1b5eeee98e
  labels:
    provider: fabric8
    project: kubeflix
    version: 1.0.26
    expose: "true"
    group: io.fabric8.kubeflix
  name: kubeflix
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      maven.fabric8.io/source-url: jar:file:/home/jenkins/workspace/workspace/kubeflix@2/turbine-server/target/turbine-server-1.0.26.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: turbine-server
      version: 1.0.26
      group: io.fabric8.kubeflix
    name: turbine
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      servicepath: /turbine.stream
      fabric8.io/git-commit: 0221779c01265c45149182dbc9860c1b5eeee98e
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: release-v1.0.26
      fabric8.io/build-id: "4"
      fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0221779c01265c45149182dbc9860c1b5eeee98e
      fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/4
      maven.fabric8.io/source-url: jar:file:/home/jenkins/workspace/workspace/kubeflix@2/turbine-server/target/turbine-server-1.0.26.jar!/META-INF/fabric8/openshift.yml
    labels:
      project: turbine-server
      provider: fabric8
      version: 1.0.26
      group: io.fabric8.kubeflix
      expose: "true"
    name: turbine-server
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: turbine-server
      provider: fabric8
      group: io.fabric8.kubeflix
    type: LoadBalancer
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 0221779c01265c45149182dbc9860c1b5eeee98e
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.26
      fabric8.io/build-id: "4"
      fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/4
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: release-v1.0.26
      fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0221779c01265c45149182dbc9860c1b5eeee98e
      maven.fabric8.io/source-url: jar:file:/home/jenkins/workspace/workspace/kubeflix@2/turbine-server/target/turbine-server-1.0.26.jar!/META-INF/fabric8/openshift.yml
    labels:
      project: turbine-server
      provider: fabric8
      version: 1.0.26
      group: io.fabric8.kubeflix
    name: turbine-server
  spec:
    replicas: 1
    selector:
      project: turbine-server
      provider: fabric8
      group: io.fabric8.kubeflix
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 0221779c01265c45149182dbc9860c1b5eeee98e
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.26
          fabric8.io/build-id: "4"
          fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/4
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: release-v1.0.26
          fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0221779c01265c45149182dbc9860c1b5eeee98e
        labels:
          project: turbine-server
          provider: fabric8
          version: 1.0.26
          group: io.fabric8.kubeflix
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/turbine-server:1.0.26
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
          name: turbine-server
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8778
            name: jolokia
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          securityContext:
            privileged: false
        serviceAccountName: turbine
    triggers:
    - type: ConfigChange
