---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.309
  labels:
    provider: fabric8
    project: logging
    version: 2.4.19
    expose: "true"
    group: io.fabric8.devops.apps
  name: logging
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/fluentd/2.2.309/fluentd-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: fluentd
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: fluentd
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/elasticsearch/2.2.309/elasticsearch-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      expose: "true"
      project: elasticsearch
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: elasticsearch
  spec:
    ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    selector:
      project: elasticsearch
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/elasticsearch/2.2.309/elasticsearch-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: elasticsearch
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: elasticsearch-masters
  spec:
    clusterIP: None
    ports:
    - name: discovery
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      project: elasticsearch
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: management
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/kibana/2.2.309/kibana-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      expose: "true"
      project: kibana
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: kibana
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5601
    selector:
      project: kibana
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/elasticsearch/2.2.309/elasticsearch-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: elasticsearch
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: es-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fluentd/src/main/fabric8/icon.png
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/fluentd/2.2.309/fluentd-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: fluentd
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: fluentd
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
        labels:
          provider: fabric8
          project: fluentd
          version: 2.2.309
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: ELASTICSEARCH_HOST
            value: elasticsearch
          - name: ELASTICSEARCH_PORT
            value: "9200"
          image: fabric8/fluentd-kubernetes:v1.19
          name: fluentd
          ports:
          - containerPort: 24231
            name: scrape
          resources:
            limits:
              cpu: 100m
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/docker/containers
            name: defaultdocker
            readOnly: true
          - mountPath: /mnt/ephemeral/docker/containers
            name: awsdocker
            readOnly: true
          - mountPath: /mnt/sda1/var/lib/docker/containers
            name: minikubedocker
            readOnly: true
        serviceAccountName: fluentd
        volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: defaultdocker
        - hostPath:
            path: /mnt/ephemeral/docker/containers
          name: awsdocker
        - hostPath:
            path: /mnt/sda1/var/lib/docker/containers
          name: minikubedocker
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v2.2.309
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/elasticsearch/2.2.309/elasticsearch-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: elasticsearch
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      project: elasticsearch
      provider: fabric8
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v2.2.309
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.309
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/usr/share/elasticsearch/data"],"volumeMounts":[{"mountPath":"/usr/share/elasticsearch/data","name":"data"}]}]'
        labels:
          provider: fabric8
          project: elasticsearch
          version: 2.2.309
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: SERVICE
            value: elasticsearch-masters
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/elasticsearch-k8s:2.3.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 9300
          name: elasticsearch
          readinessProbe:
            httpGet:
              path: /_template/logstash
              port: 9200
            initialDelaySeconds: 5
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
        - image: fabric8/elasticsearch-logstash-template:2.2.309
          name: logstash-template
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: es-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.309
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.309
      maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/devops/apps/kibana/2.2.309/kibana-2.2.309.jar!/META-INF/fabric8/openshift.yml
    labels:
      provider: fabric8
      project: kibana
      version: 2.2.309
      group: io.fabric8.devops.apps
    name: kibana
  spec:
    replicas: 1
    selector:
      project: kibana
      provider: fabric8
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: d324cb9a7887f68434a053aa047bd9374d451485
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
          fabric8.io/git-branch: release-v2.2.309
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.309
        labels:
          provider: fabric8
          project: kibana
          version: 2.2.309
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/kibana4:v4.5.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 5601
          name: kibana
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 5
          securityContext:
            privileged: false
        - env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          image: fabric8/kibana-config:2.2.309
          name: logstash-template
    triggers:
    - type: ConfigChange
