---
apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
    maven.fabric8.io/app-catalog: "true"
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.303
  labels:
    provider: fabric8
    project: manageiq
    version: 2.2.303
    expose: "true"
    group: io.fabric8.devops.apps
  name: manageiq
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
      fabric8.io/app-menu: management
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
    labels:
      provider: fabric8
      project: manageiq
      version: 2.2.303
      group: io.fabric8.devops.apps
      expose: "true"
    name: manageiq
  spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: 443
    selector:
      project: manageiq
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
      fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
      fabric8.io/git-branch: release-v2.2.303
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=manageiq&var-version=2.2.303
    labels:
      provider: fabric8
      project: manageiq
      version: 2.2.303
      group: io.fabric8.devops.apps
    name: manageiq
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: manageiq
      group: io.fabric8.devops.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
          fabric8.io/git-commit: 692764ddc65dfe31586a49a466060b5bf223f6f5
          fabric8.io/git-branch: release-v2.2.303
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=manageiq&var-version=2.2.303
        labels:
          provider: fabric8
          project: manageiq
          version: 2.2.303
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: manageiq/manageiq:latest
          imagePullPolicy: IfNotPresent
          name: manageiq
          readinessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: true
    triggers:
    - type: ConfigChange
